### ISSUE TITLE
add css-in-js strategy

### ISSUE THREAD

**Issue by santospatrick** [agrotis-io/vraw#19]
### What are you reporting?

* [ ] Bug that needs fixing
* [ ] Feature
* [ ] Code refactor
* [ ] Continuous Integration (CI) improvement
* [ ] Changes in documentation (docs)
* [X] Other

### What is the current behavior?

We need to analyze and discuss which package the project needs to add support to css-in-js

### What is the expected behavior?

Have a mature lib to apply css-in-js better than react's defaults way to implement

### Which problem(s) will it solve?

Styling inside React Components

### Which versions of React and TypeScript are you using?

--

### What is your environment?

> Version: 1.0.4
> OS: Linux Mint 17.3 Cinnamon 64-bit
> Browser: Chrome 65 (64 bits)
> Node version: 8.9.4
> Device: Notebook Lenovo E431

**Comment by santospatrick** [comment]
i vote for styled-components, what do you guys think?

**Comment by jhserodio** [comment]
why?

**Comment by eliandersoh** [comment]
Styled components provide a clean way to work with css-in-js on react components:
- It removes the mapping between components and styles
- Support both react and react native 
- Has [theming support](https://www.styled-components.com/docs/advanced#theming) that can help on issue #20 
- Has basic sass support
- Since version 3 it has better [performance.](https://medium.com/styled-components/v3-1-0-such-perf-wow-many-streams-c45c434dbd03)
- Has a large support community
- Has more than 14k star on github
- Large companies like atlassian use on [its components library](https://atlaskit.atlassian.com/)

**Comment by jhserodio** [comment]
and the others libraries, tools?
why has react native support?
why styled components and not pure css and css modules?
this is better solution compare between ?

we need a strategy and analysis thinking in the raw and your use case, not a list of advantages of a library.

**Comment by santospatrick** [comment]
From what i read so far:

| Package | Props Access | TypesScript Support | Media Queries | Theme Support | Component Inner Reference |
|------------|---------------------|-----------------------------|--------------------|----------------------|--------|
| [emotion](https://github.com/emotion-js/emotion) | yes | [kindof](https://emotion.sh/docs/typescript) | yes | yes | yes |
| [styled-components](https://www.styled-components.com/) | yes | [yes](https://www.styled-components.com/docs/api#typescript) | yes | yes | yes |
| [aphrodite](https://github.com/Khan/aphrodite) | [kindof](https://www.reddit.com/r/reactjs/comments/6y7vqb/how_to_pass_prop_style_data_from_parent_to_child/) | [yes](https://www.npmjs.com/package/@types/aphrodite) | yes | [kindof](https://github.com/Khan/aphrodite/issues/141#issuecomment-249117388) | not needed |

We also have [glamorous](https://glamorous.rocks/) which is very much like styled-components (also inspired in), rocks all the columns in that table and at this point they made [css in js autocomplete](https://blog.kentcdodds.com/glamorous-v4-is-here-c678fe02a39a), which i find really helpful for less docs reading and fast coding when using our repo, what do you guys think? Also, we have a [big guy](https://kentcdodds.com/) in this project.

**Comment by jhserodio** [comment]
the syntax and usage is very different between styled-components/styled-jsx and glamour.

**Comment by santospatrick** [comment]
@jhserodio why different usage?

**Comment by jhserodio** [comment]
syntax is different, glamor is how to react css in js, others like css. The use is different in principles, with glamor you create styles with various syntax if you use external codes.

analyze these topics:
- performance
- environment
- community adherence
- support and compatibility with already existing dependencies

We can not choose something now that ends up being discontinued, causing a major impact on all development, to be honest, the closer to native technology, the easier it is to deal with future changes.

**Comment by santospatrick** [comment]
I'm on glamorous now because we can work with [existing css](https://glamorous.rocks/advanced/#working-with-existing-css) easily, then we can extend from libs that aren't react specific, like [material.io](https://material.io/components/).
